#!/bin/bash

#######################################################
## This page is built with Pandoc using markdown. Site 
## navigation is created with Pandoc's 
## include-before-body function by inserting nav.html
## into every page's HTML when it is built by Pandoc.
####################################################### 

#Intro
pandoc ./markdown/intro.md \
--css style.css \
--template ./templates/main.html \
--output index.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="Introduction"

#Methods
pandoc ./markdown/methods.md \
--css style.css \
--template ./templates/main.html \
--output methods.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="Methodology"

#Data Janitorial Work
pandoc ./markdown/janitor.md \
--css style.css \
--template ./templates/main.html \
--output janitor.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="Data Janitorial Work"

#Statistical Reasoning
pandoc ./markdown/stats.md \
--css style.css \
--template ./templates/main.html \
--output stats.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="Statistical Reasoning" 

#Conclusion
pandoc ./markdown/conclusion.md \
--css style.css \
--template ./templates/main.html \
--output conclusion.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="Conclusion" 

#Notes and References
pandoc ./markdown/notes.md \
--css style.css \
--template ./templates/main.html \
--output notes.html \
--smart \
--include-before-body ./templates/nav.html \
--include-after-body ./templates/footer.html \
--title-prefix="References"
